### ISSUE TITLE
use sklt alongside i3status

### ISSUE THREAD

**Issue by amir28** [shibe2/sklt#3]
Hello, I had a problem that i3status does not show my keyboard layout. I tried some plugins and apps to solve that but not succeed. Today I tried sklt and it works perfectly. But I can't use i3status to show some information(like root free space, ipv4 and etc)
my sway configuration is:
```
...
bar {
    position top

    # When the status_command prints a new line to stdout, swaybar updates.
    # The default just shows the current date and time.
    # status_command while date +'%Y-%m-%d %l:%M:%S %p'; do sleep 1; done
	#status_command i3status 
	status_command i3status | "~/go/bin/sklt -x ~/go/src/github.com/shibe2/sklt/layouts.tsv"
        # OR
        status_command  ~/go/bin/sklt -x ~/go/src/github.com/shibe2/sklt/layouts.tsv | i3status
    colors {
	separator #444444
	background #222222
	statusline #B1B1B1
	focused_workspace #CECECE #CECECE #000000
	active_workspace #333333 #333333 #888888
	inactive_workspace #CECECE #333333 #f1f1f1
	urgent_workspace #eb709b #eb709b #ffffff
   }
}
... 
```

Thanks

**Comment by shibe2** [comment]
SKLT does not use standard input, so you can't pipe data to it. In i3status you can try something like

    read_file sklt {
        path = "/dev/stdin"
    }

and pipe from SKLT, like in your second example. If that doesn't work, you'll need a third program or a script that will combine outputs of 2 other programs.

Though I'd say, SKLT is not the right program for your use case. Check out [Waybar](https://github.com/Alexays/Waybar).

**Comment by amir28** [comment]
Thank You It works prefect :)))
